# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5bdff581269708afe0174af9f87eb184a473a44becfe14efaae82337b31d9e62e447537455c32ca8e8fd66427b689998bad6c67498a6df37743d9fb8e9f64d0

test:
  secret_key_base: d79940ca70ff8327b50cbc1a54ccb4302c1a6ea2d319510cf648c249d6c37f0fc440dc9337ccf542e500fa63a421ad362044b759310f5c417ac888caa18d8c3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
